services:
  mysql:
    image: mysql:8.0
    container_name: todo-api
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: todo-api
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - "3306:3306"